### ISSUE TITLE
Default Font / Usage Question

### ISSUE THREAD

**Issue by sprjr** [jamesplease/materialish#205]
Hello 👋

I'm sorry if this is already explained, but I just tossed this into a `create-react-app` generated page. I noticed that the default variables that ship with this are `Roboto`, but the documentation currently only has individual component usage guides so I didn't see anywhere that indicated that I'd _also_ need to import Roboto either on my system or directly from Google.

Since I didn't see that, I thought maybe the imported CSS files might already include that - and it looks like it does not!

I'm assuming the correct 'using these components in your app' includes adding Roboto yourself, and that the component CSS files only have the styles / variables related _directly_ to them, correct?

**Comment by jamesplease** [comment]
:wave: Hey there!

> I'm sorry if this is already explained

It's not explicitly stated. I plan to write a more detailed guide regarding the CSS, but I haven't gotten around to it.

> the documentation currently only has individual component usage guides so I didn't see anywhere that indicated that I'd also need to import Roboto either on my system or directly from Google.

Yup, you are responsible for loading your own Roboto.

> Since I didn't see that, I thought maybe the imported CSS files might already include that - and it looks like it does not!

Correct, we don't import Roboto for you.

> I'm assuming the correct 'using these components in your app' includes adding Roboto yourself, and that the component CSS files only have the styles / variables related directly to them, correct?

Yup!

You can change the font globally using `--mt-fontFamily`, which is documented on each component's individual API page underneath the "CSS Variables" section (such as on the [Button](https://materialish.js.org/components/button) page)
