### ISSUE TITLE
CSS Vars

### ISSUE THREAD

**Issue by JPorry** [jamesplease/materialish#8]
Decide the naming and what things are we going to allow css vars customization and apply it to all components in the repo

**Comment by jamesplease** [comment]
@JPorry and I chatted offline about this. We are thinking of the following:

1. every variable used in materialish has the `mt` prefix.
2. variables are named like `mt-{component}-{attribute}` or `mt-{attribute}`. Camel cased names will be used between the hyphens. i.e. `mt-mainColor` or `mt-button-borderRadius`
3. we will use underscored variable names internally as a shorthand for `var(publicInterface, default)`

**Comment by jamesplease** [comment]
Closing. The only component right now is the button, and it adheres to this
